### PR TITLE
Fixes of DIC extension

### PR DESCRIPTION
**Pull request by hrach**

### CODE REVIEW

**Comment by hrach** [comment]
Please, disable this nonsense sniff:
FILE: /home/travis/build/contributte/redis/src/DI/RedisExtension.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 146 | ERROR | Variable "$name" not allowed in double quoted string;
     |       | use sprintf() instead
     |       | (Squiz.Strings.DoubleQuoteUsage.ContainsVar)

**Comment by f3l1x** [comment]
Thanks for the PR. 👏 

This is our ruleset for the all contributte's packages. Please respect it.

**Comment by hrach** [comment]
This is really sad story. Obviously you have activated nonsense sniff and forcing people to modify their code to this. Neither the result is more readable, secure, nor standardized, whatever. I ashamed I had to push such code.

**Comment by hrach** [comment]
```php
"@connection.$name.client"
```
vs. pushed (to be consistent)
```php
'@connection.' . $name . '.client'
```
vs. suggested by sniff (🤦‍♂️)
```php
sprintf('@connection.%s.client', $name)
```

**Comment by paveljanda** [comment]
@hrach I personally prefer the `sprintf` version. As a matter of fact, many beginning programmers tend to mix `"` vs `'` and other magics in the string interpolation. `sprintf` version is strict and safe. :)

**Comment by JanTvrdik** [comment]
I don't understand what you mean by more safe. You mean if programmer remembers to use `%d` instead of `%s`?

**Comment by paveljanda** [comment]
I just think that people tend to do more mistakes in string interpolation `"foo$barBaz.boom"` than when calling `sprintf`. It is just my experience (and yes, also me personally..).

When I have to use string interpolation I use at least the curly syntax: `foo"{barBaz}.boom"`.

PS: I don't use IDE.

**Comment by paveljanda** [comment]
But I understand this is just my personal opinion. When there is some package requiring string interpolation or string concatenation or `sprintf`, let's do it the way they want to. Eventually, it is their preference and not that big problem for us to change the code.

**Comment by f3l1x** [comment]
Thanks for the PR @hrach

**Comment by hrach** [comment]
Thanks :)

**Pull request merged**
