### PR TITLE
Added snappy serializer

### PR DESCRIPTION
**Pull request by jakubvojacek**
adds support for snappy serializer (required snappy to be installed https://github.com/krakjoe/snappy)

### CODE REVIEW

**Comment by f3l1x** [comment]
Add some test please, take a look at Igbinary test. Thank you.

**Comment by jakubvojacek** [comment]
`snappy_(un)compress` is not installed in GA (thats why phpstan test failed), i got zero experience with github, do you know how to install it? 

Are the tests for serializers really necessary? Its a single function with no logic involved, its as if you'd test `strlen('a') === 1`, thats outside the scope of this library and should be tested at the PHP/snappy/igbinary level

**Comment by f3l1x** [comment]
I will fix github/phpstan. I see big pros of this test. 

1. It will show us structure of serialized data. For example, I don't know how it looks like using snappy.
2. It will show us if format of serialized data would change.
3. It will show us if SnappySerializer works. Maybe it's very simple class at this moment, but it wouldn't be in the future. It will help us trust the code and don't be afraid of changing.

**Comment by jakubvojacek** [comment]
> I will fix github/phpstan. I see big pros of this test.
> 
> 1. It will show us structure of serialized data. For example, I don't know how it looks like using snappy.
> 2. It will show us if format of serialized data would change.
> 3. It will show us if SnappySerializer works. Maybe it's very simple class at this moment, but it wouldn't be in the future. It will help us trust the code and don't be afraid of changing.

I added the tests, lets see whether they pass once snappy module is added

**Pull request merged**
