### PR TITLE
CI: php 8.1 in matrix

### PR DESCRIPTION
**Pull request by grogy**
I tested it live with project www.estatoid.cz and work's for session handling great.

### CODE REVIEW

**Comment by f3l1x** [comment]
Thanks

**Comment by f3l1x** [comment]
Can you add you or your company here https://contributte.org/partners.html?

**Comment by grogy** [comment]
Thanks for the merge. 

Adding to partners - Does it make sense for you? If yes so I agree :-)

**Comment by f3l1x** [comment]
Sure, big time.

**Comment by grogy** [comment]
What should I do?

**Comment by f3l1x** [comment]
There is a repo for that. Pick one of the list. Just create a issue for that and I will do the rest.

https://github.com/contributte/contributte#connecting

**Pull request merged**
