### PR TITLE
Run E2E tests with actual Redis

### PR DESCRIPTION
**Pull request by jankonas**
Suggestions how to add redis and keep remote nette-tester template are welcome :-)

### CODE REVIEW

**Comment by f3l1x** [comment]
Hi @jankonas, can you please create nette-tester-redis in contributte/.github repo? Similar to https://github.com/contributte/.github/blob/master/.github/workflows/nette-tester-mysql.yml, thanks.

**Comment by jankonas** [comment]
> Hi @jankonas, can you please create nette-tester-redis in contributte/.github repo? Similar to https://github.com/contributte/.github/blob/master/.github/workflows/nette-tester-mysql.yml, thanks.

Sure https://github.com/contributte/.github/pull/6

**Comment by f3l1x** [comment]
Done. Please use `nette-tester-redis.yml@master`

**Comment by jankonas** [comment]
> Done. Please use `nette-tester-redis.yml@master`

Done :-)

**Comment by f3l1x** [comment]
👍

**Comment by f3l1x** [comment]
Can you please rebase it? @jankonas

**Pull request merged**
