### PR TITLE
Update readme: add sessions and cache config example

### PR DESCRIPTION
**Pull request by dakorpar**

### CODE REVIEW

**Comment by fmasa** [comment]
I think it would be better to remove this collision of sessions and cache entries (as I mentioned in https://github.com/contributte/redis/issues/14#issuecomment-748540409) as it's not always possible to use multiple databases. WDYT? @dakorpar @f3l1x

**Comment by dakorpar** [comment]
@fmasa we use sentinel replication and I didn't even know on redis cluster only one db is supported.
Can U then maybe add PR and we can close this one?
Maybe we should read this from options somehow as well?
Although prefixing keys does sound good TBH. even adding option to config for first prefix, like project1, project2:
and then
project1:cache
project2:cache
It would also allow multiple project on same redis cluster/sentinel, whatever setup...

**Comment by fmasa** [comment]
We use Sentinel as well. Anyway app-wide prefix can be configured using `prefix` option of Predis, so there is no reason for additional support IMO

**Comment by f3l1x** [comment]
Merging this PR, it updates docs. What about next PR according to things you have discussed here? Any conclusion in here or [here](https://github.com/contributte/redis/issues/14#issuecomment-751464245)?

**Pull request merged**
